// For publishing you should provide credentials. Assuming that you have them somewhere in a file of format: 
//   accessKey = 322wasa923...
//   secretKey = 2342xasd8fDfaa9C...
// Just provide the full path to this file and delete this comment. (Note, this file won't be tracked by git).

// s3credentialsFile := Some("/absolute/path/to/your/file/with/amazon/credentials.propeties")
